name: Axel Segebrecht
description: adventures in digital advancement
meta_description: "Axel Segebrecht's blog"


markdown: redcarpet
highlighter: pygments

paginate: 50
baseurl: /
domain_name: 'https://axelsegebrecht.com'
google_analytics: ''
disqus_shortname: 'axelsegebrecht'

# Details for the RSS feed generator
url:            'https://axelsegebrecht.com'
author:         'Axel Segebrecht'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
